/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge9;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    public void testReverseLinkedList() {
        // Arrange
        reverseArray list = new reverseArray();
        list.append(1);
        list.append(2);
        list.append(3);

        // Act
        list.reverseLinkedList();

        // Assert
        assertEquals("head > 3 > 2 > 1", list.toString());
    }

    @Test
    public void testReverseEmptyLinkedList() {
        // Arrange
        reverseArray list = new reverseArray();

        // Act
        list.reverseLinkedList();

        // Assert
        assertEquals("head", list.toString());
    }


}
