/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

public class Library {
    public static void main (String [] args){
        pseudoQueue PQ= new pseudoQueue();
        PQ.enqueue(20);
        PQ.enqueue(15);
        PQ.enqueue(10);
        PQ.enqueue(5);
        System.out.println(PQ);
        System.out.println(PQ.dequeue());
        System.out.println(PQ);
        System.out.println(PQ.dequeue());
        System.out.println(PQ);




            }
}
