/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.business.trip;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


        @Test
        public void testGraphAddEdge() {
            Graph graph = new Graph();
            graph.addEdge("A", "B", 10);
            assertEquals(10, graph.getNeighbors("A").get("B").intValue());
        }

        @Test
        public void testGraphGetNeighbors() {
            Graph graph = new Graph();
            graph.addEdge("X", "Y", 15);
            graph.addEdge("X", "Z", 20);
            assertEquals(15, graph.getNeighbors("X").get("Y").intValue());
            assertEquals(20, graph.getNeighbors("X").get("Z").intValue());
        }

        @Test
        public void testBusinessTripWithDirectFlights() {
            Graph graph = new Graph();
            graph.addEdge("City1", "City2", 30);
            graph.addEdge("City2", "City3", 50);
            graph.addEdge("City3", "City4", 40);

            BusinessTrip businessTrip = new BusinessTrip();
            List<String> trip = Arrays.asList("City1", "City2", "City3", "City4");
            assertEquals(30 + 50 + 40, businessTrip.businessTrip(graph, trip).intValue());
        }

        @Test
        public void testBusinessTripWithMissingFlight() {
            Graph graph = new Graph();
            graph.addEdge("A", "B", 25);
            graph.addEdge("B", "C", 30);
            graph.addEdge("D", "E", 45);

            BusinessTrip businessTrip = new BusinessTrip();
            List<String> trip = Arrays.asList("A", "B", "D", "E");
            assertNull(businessTrip.businessTrip(graph, trip));
        }

        @Test
        public void testBusinessTripWithSingleCity() {
            Graph graph = new Graph();
            BusinessTrip businessTrip = new BusinessTrip();
            List<String> trip = Arrays.asList("City1");
            assertEquals(0, businessTrip.businessTrip(graph, trip).intValue());
        }

}