/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package treeIntersection;

import org.junit.jupiter.api.Test;
import treeIntersection.TreeIntersection.Node;
import treeIntersection.TreeIntersection.TreeIntersection;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testFindCommonValuesWithCommonValues() {
        TreeIntersection treeIntersection = new TreeIntersection();

        Node root1 = new Node(1);
        root1.left = new Node(2);
        root1.right = new Node(3);

        Node root2 = new Node(3);
        root2.left = new Node(5);
        root2.right = new Node(6);

        Set<Integer> result = treeIntersection.findCommonValues(root1, root2);
        Set<Integer> expected = Set.of(3);

        assertEquals(expected, result);
    }

    @Test
    public void testFindCommonValuesWithoutCommonValues() {
        TreeIntersection treeIntersection = new TreeIntersection();


        Node root1 = new Node(1);
        root1.left = new Node(2);
        root1.right = new Node(3);

    Node root2 = new Node(4);
        root2.left = new Node(5);
        root2.right = new Node(6);

        Set<Integer> result = treeIntersection.findCommonValues(root1, root2);
        Set<Integer> expected = Set.of();

        assertEquals(expected, result);
    }
}
