/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge14;

public class Library {

    public static void main (String [] args){
        try {
   GetMax getMax=new GetMax();
        getMax.push(4);
        getMax.push(7);
        getMax.push(3);
        getMax.push(9);
        getMax.push(2);

        System.out.println("max value = " + getMax.getMaxValue());

        getMax.pop();
        getMax.pop();
        System.out.println("max value after pop = " + getMax.getMaxValue());
        getMax.pop();
        getMax.pop();

        System.out.println("max value after pop = " + getMax.getMaxValue());
        getMax.pop();
        System.out.println("max value after pop = " + getMax.getMaxValue());

        } catch (RuntimeException e) {
            System.out.println("Stack is empty.");
        }
    }

    }

