/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    private hashTable<String, Integer> hashtable;



    @Test
    public void testSetAndGet() {
        hashtable = new hashTable<>(100);
        hashtable.set("ghofran", 5);
        int value = hashtable.get("ghofran");
        assertEquals(5, value);
    }

    @Test
    public void testGetNonExistentKey() {
        hashtable = new hashTable<>(100);
        assertNull(hashtable.get("amal"));
    }

    @Test
    public void testKeys() {
        hashtable = new hashTable<>(100);
        hashtable.set("apple", 5);
        hashtable.set("banana", 2);
        hashtable.set("cherry", 8);

        List<String> keys = hashtable.keys();
        assertTrue(keys.contains("apple"));
        assertTrue(keys.contains("banana"));
        assertTrue(keys.contains("cherry"));
        assertEquals(3, keys.size());
    }

    @Test
    public void testCollision() {
        hashtable = new hashTable<>(2);
        hashtable.set("ghofran", 7);
        hashtable.set("marwah", 6);

        int value1 = hashtable.get("ghofran");
        int value2 = hashtable.get("marwah");

        assertEquals(7, value1);
        assertEquals(6, value2);
    }

    @Test
    public void testRetrieveCollision() {
        hashtable = new hashTable<>(2);
        hashtable.set("apple", 5);
        hashtable.set("banana", 2);

        int value1 = hashtable.get("apple");
        int value2 = hashtable.get("banana");

        assertEquals(5, value1);
        assertEquals(2, value2);
    }

    @Test
    public void testHashInRange() {
        hashtable = new hashTable<>(100);
        int hashValue = hashtable.hash("ghofrandaradkh");
        assertTrue(hashValue >= 0 && hashValue < 100);
    }
}
