/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

public class Library {
    AnimalShelter shelter = new AnimalShelter();

    // Adding animals to the shelter


}
