/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghraphs;

import java.util.Collection;
import java.util.List;

public class Library {
    public static void main(String[] args) {
        Graphs graph = new Graphs();

        Vertex vertex1 = graph.addVertex("pandora");
        Vertex vertex2 = graph.addVertex("Arendelle");
        Vertex vertex3 = graph.addVertex("Metroville");
        Vertex vertex4 = graph.addVertex("Monstroplolis");


        graph.addEdge(vertex1, vertex2, 5);
        graph.addEdge(vertex1, vertex3, 3);
        graph.addEdge(vertex1, vertex4, 6);

        List<Vertex> breadthFirstTraversal = graph.breadthFirst(vertex1);

        System.out.println("\nGraph size: " + graph.size());

        System.out.println("Vertices:");
        Collection<Vertex> vertices = graph.getVertices();
        for (Vertex vertex : vertices) {
            System.out.println(vertex.getValue());
        }

        System.out.println("\nNeighbors of vertex1:");
        Collection<Edge> neighbors = graph.getNeighbors(vertex1);
        for (Edge edge : neighbors) {
            System.out.println("start vertex:"+edge.getStart().getValue()+ " , End vertex: " + edge.getEnd().getValue() + ", Weight: " + edge.getWeight());
        }

        System.out.println("\nGraph size: " + graph.size());
    }


}
