/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghraphs;

import java.util.Collection;

public class Library {
    public static void main(String[] args) {
        Graphs graph = new Graphs();

   Vertex vertex1 = graph.addVertex(1);
   Vertex vertex2 = graph.addVertex(2);
      Vertex vertex3 = graph.addVertex(3);
//        Vertex vertex4 = graph.addVertex(4);


        graph.addEdge(vertex1, vertex2, 5);
        graph.addEdge(vertex1, vertex3, 3);
//        graph.addEdge(vertex1, vertex4, 6);



        System.out.println("Vertices:");
        Collection<Vertex> vertices = graph.getVertices();
        for (Vertex vertex : vertices) {
            System.out.println(vertex.getValue());
        }

        System.out.println("\nNeighbors of vertex1:");
        Collection<Edge> neighbors = graph.getNeighbors(vertex1);
        for (Edge edge : neighbors) {
            System.out.println("start vertex:"+edge.getStart().getValue()+ " , End vertex: " + edge.getEnd().getValue() + ", Weight: " + edge.getWeight());
        }

        System.out.println("\nGraph size: " + graph.size());
    }
}
