/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghraphs;

import java.util.Collection;
import java.util.List;

public class Library {
    public static void main(String[] args) {
        Graphs <String> graph = new Graphs<String>();

        Vertex<String> vertexA = graph.addVertex("A");
        Vertex<String> vertexB = graph.addVertex("B");
        Vertex<String> vertexC = graph.addVertex("C");
        Vertex<String> vertexD = graph.addVertex("D");
        Vertex<String> vertexE = graph.addVertex("E");
        Vertex<String> vertexF = graph.addVertex("F");
        Vertex<String> vertexG = graph.addVertex("G");
        Vertex<String> vertexH = graph.addVertex("H");

        graph.addEdge(vertexA, vertexB, 0);
        graph.addEdge(vertexB, vertexC, 0);
        graph.addEdge(vertexB, vertexD, 0);
        graph.addEdge(vertexD, vertexE, 0);
        graph.addEdge(vertexC, vertexG, 0);
        graph.addEdge(vertexG, vertexH, 0);
        graph.addEdge(vertexD, vertexH, 0);
        graph.addEdge(vertexF, vertexH, 0);
        graph.addEdge(vertexH, vertexF, 0);


        List<Vertex<String>> traversalResult = graph.breadthFirst(vertexA);


        System.out.println("Breadth-First Traversal: " + traversalResult);

        List<Vertex<String>> traversalResult2 = graph.depthFirst(vertexA);


        System.out.println("Depth-First Traversal: " + traversalResult2);

        System.out.println("\nGraph size: " + graph.size());

        System.out.println("Vertices:");
        Collection<Vertex<String>> vertices = graph.getVertices();
        for (Vertex vertex : vertices) {
            System.out.println(vertex.getValue());
        }

        System.out.println("\nNeighbors of vertex1:");
        Collection<Edge<String>> neighbors = graph.getNeighbors(vertexA);
        for (Edge edge : neighbors) {
            System.out.println("start vertex:"+edge.getStart().getValue()+ " , End vertex: " + edge.getEnd().getValue() + ", Weight: " + edge.getWeight());
        }

        System.out.println("\nGraph size: " + graph.size());
    }


}
