/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenge34;

public class Library {
    public static void main(String[] args) {
  hashtable hashtable=new hashtable();
        System.out.println(hashtable.hasUniqueCharacters("The quick brown fox jumps over the lazy dog")); // Should return false
        System.out.println(hashtable.hasUniqueCharacters("I love cats"));                                 // Should return true
        try {
            System.out.println(hashtable.hasUniqueCharacters(""));
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage()); // Print the exception message
        }

        // Should return false
    }
}
