/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated;



public class Library {
    public static void main(String[] args) {
  hashMapReapeted hashMapReapeted=new hashMapReapeted();
        System.out.println(hashMapReapeted.repeatedWord("Once upon a time, there was a brave princess who..."));
        System.out.println(hashMapReapeted.repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..."));
        System.out.println(hashMapReapeted.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."));
        System.out.println(hashMapReapeted.repeatedWord(""));
    }

}
