/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.fizz.buzz;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test
    void testFizzBuzzTree() {

        treeFizzBuzz tree = new treeFizzBuzz();
        tree.root = tree.new Node(4);
        tree.root.child = tree.new Node(30);
        tree.root.child.child = tree.new Node(1);
        tree.root.child.child.child = tree.new Node(20);
        tree.root.child.child.child.child = tree.new Node(3);

        List<String> result = tree.fizzBuzzTree();

        // Expected result for the sample tree:
        // ["4", "FizzBuzz", "1", "Buzz", "Fizz"]

        assertEquals(5, result.size());
        assertEquals("4", result.get(0));
        assertEquals("FizzBuzz", result.get(1));
        assertEquals("1", result.get(2));
        assertEquals("Buzz", result.get(3));
        assertEquals("Fizz", result.get(4));
    }
}

