/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package treeIntersection;

import treeIntersection.TreeIntersection.Node;
import treeIntersection.TreeIntersection.TreeIntersection;

import java.util.Set;

public class Library {
    public static void main(String[] args) {
        TreeIntersection treeIntersection = new TreeIntersection();


        Node root1 = new Node(1);
        root1.left = new Node(2);
        root1.right = new Node(3);
        root1.left.left = new Node(4);
        root1.left.right = new Node(5);

     Node root2 = new Node(3);
        root2.left = new Node(5);
        root2.right = new Node(7);


        Set<Integer> commonValues = treeIntersection.findCommonValues(root1, root2);

        System.out.println("Common values: " + commonValues);
    }
}
