/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated;

import org.junit.jupiter.api.Test;

import static hashmap.repeated.hashMapReapeted.*;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test

    public void testRepeatedWordInSentence() {
        hashMapReapeted hashMapReapeted=new hashMapReapeted();
        String input = "Once upon a time, there was a brave princess who";
        String result = hashMapReapeted.repeatedWord(input);
        assertEquals("a", result);
    }




    @Test
    public void testNoRepeatedWords() {
   hashMapReapeted hashMapReapeted=new hashMapReapeted();
        String input = "This is a test sentence.";
        String result = hashMapReapeted.repeatedWord(input);


        assertNull(result);
    }

    @Test
    public void testNoWordsInInput() {
        hashMapReapeted hashMapReapeted=new hashMapReapeted();
        String input = "";
        String result = hashMapReapeted.repeatedWord(input);
        assertNull(result);
    }



    }

