/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maxtrees;

public class Library {
    public static void main(String [] args){

        treeMax max=new treeMax();
        max.add(1);
        max.add(15);
        max.add(11);
        max.add(21);
        max.add(14);
        max.add(17);

        System.out.println(max.findMaximumValue());


    }


}
