/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge5linkedlist;



public class Library {
    public static void main(String[] args) {
        //create list
        challenge5.LinkedList list = new challenge5.LinkedList();


        list.linkedListInsert(10);
        list.linkedListInsert(20);
        list.linkedListInsert(30);


        System.out.println(list.linkedListToString());
        System.out.println(list.linkedListInclude(5));

    }
}
